CREATE DATABASE IF NOT EXISTS startersql;
USE startersql;

CREATE TABLE companyMembers (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) UNIQUE NOT NULL,
gender ENUM ("MALE", "FEMALE", "OTHER"),
DOB DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

